[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = [
  'python -m pip install --upgrade pip',
  'pip install --no-cache-dir -r requirements.txt'
]

[phases.build]
cmds = [
  'python manage.py collectstatic --noinput'
]

[start]
cmd = 'bash start.sh'


